---
abstract: 'log events to Message::Passing'
author:
  - 'Tomas Doran (t0m) C<< <bobtfish@bobtfish.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: agpl_3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Log::Dispatch::Message::Passing
name: Log-Dispatch-Message-Passing
no_index:
  directory:
    - example
    - inc
    - t
requires:
  Log::Dispatch: 0
  Message::Passing: 0.006
  Scalar::Util: 0
resources:
  repository: git://github.com/suretec/Log-Dispatch-Message-Passing.git
version: 0.007
x_authority: GHENRY
